.PHONY: clean All

All:
	@echo "----------Building project:[ Ejemplo22 - Debug ]----------"
	@cd "Ejemplo22" && "$(MAKE)" -f  "Ejemplo22.mk"
clean:
	@echo "----------Cleaning project:[ Ejemplo22 - Debug ]----------"
	@cd "Ejemplo22" && "$(MAKE)" -f  "Ejemplo22.mk" clean
