.PHONY: clean All

All:
	@echo "----------Building project:[ Ejemplo23 - Debug ]----------"
	@cd "Ejemplo23" && "$(MAKE)" -f  "Ejemplo23.mk"
clean:
	@echo "----------Cleaning project:[ Ejemplo23 - Debug ]----------"
	@cd "Ejemplo23" && "$(MAKE)" -f  "Ejemplo23.mk" clean
