.PHONY: clean All

All:
	@echo "----------Building project:[ Ejemplo2.4 - Debug ]----------"
	@cd "Ejemplo2.4" && "$(MAKE)" -f  "Ejemplo2.4.mk"
clean:
	@echo "----------Cleaning project:[ Ejemplo2.4 - Debug ]----------"
	@cd "Ejemplo2.4" && "$(MAKE)" -f  "Ejemplo2.4.mk" clean
