.PHONY: clean All

All:
	@echo "----------Building project:[ Ejemplo2.1 - Debug ]----------"
	@cd "Ejemplo2.1" && "$(MAKE)" -f  "Ejemplo2.1.mk"
clean:
	@echo "----------Cleaning project:[ Ejemplo2.1 - Debug ]----------"
	@cd "Ejemplo2.1" && "$(MAKE)" -f  "Ejemplo2.1.mk" clean
